### ISSUE TITLE
Cost of card feature no longer saving.

### ISSUE THREAD

**Issue by venusjems** [webrender/trello-costello#11]
Is there a limit of how many cards the Cost feature can be placed on? We are adding the cost to cards and the newest ones are no longer saving. (ones previously placed last week are still showing up- any new costs are not remaining/showing to other users)

**Comment by webrender** [comment]
hey, thanks for reporting this! trello sets a limit of 4,000 characters per stored data object, and i have a feeling that you're running into that limitation.  currently, costello sets all the costs in a single board-level object;  a solution to this would be to store costs individually on the cards they are assigned to.  look for an update that fixes this in the next few days :)

out of curiosity, approximately how many cards does your board have costs set for?

**Comment by venusjems** [comment]
We got them on about 110 cards give or take. Still have another 100-150 remaining that will not take.

**Comment by venusjems** [comment]
Is there any update on this? It still is not saving.
(We are already placing the cost on each individual card- Old ones are saving new ones are not)

**Comment by webrender** [comment]
Alrighty, after some initial stumbles I've pushed an update tonight that refactors Costello to use card-level data instead of board-level data, along with a conversion function to update old costs to use the new data objects. Let me know if it works properly for you!
